#Hunspell dictionaries path
# will look for dictionaries at ~/.local/share/fastspell if empty
dictpath: ""

#This is how hunspell files (.dic and .aff) are named in dictpath
hunspell_codes:
    bg: bg_BG
    ca: ca_ES
    gl: gl_ES
    nb: nb_NO
    nn: nn_NO
    sv: sv_SE
    da: da_DK
    is: is_IS
    de: de_DE
    hu: hu_HU
    et: et_ET
    bs: bs_BA
    cs: cs_CZ
    sk: sk_SK
    hr: hr_HR
    me: sr_ME
    mk: mk_MK
    sq: sq_AL
    sr: sr_RS
    sl: sl_SI
    es: es_ES
    pt: pt_PT
    nl: nl_NL
    af: af_ZA
    hbs_lat: hr_HR
    hbs_cyr: sr_RS
    ru: ru_RU
