#Hunspell dictionaries path
# will look for dictionaries at ~/.local/share/fastspell if empty
dictpath: ""

#This is how hunspell files (.dic and .aff) are named in dictpath
hunspell_codes:
    af: af_ZA
    an: an_ES
    ar: ar
    az: az_AZ
    be: be_BY
    bg: bg_BG
    bn: bn_BD
    bs: bs_BA
    ca: ca_ES
    cs: cs_CZ
    cy: cy_GB
    da: da_DK
    de: de_DE
    en: en_GB
    es: es_ES
    et: et_ET
    fa: fa_IR
    fi: fi_FI
    fo: fo
    ga: ga
    gl: gl_ES
    gu: gu_IN
    hbs_lat: hbs_Lat_HBS
    hbs_cyr: hbs_Cyr_HBS
    he: he_IL
    hi: hi_IN
    hr: hr_HR
    hu: hu_HU
    id: id_ID
    is: is_IS
    iw: he_IL
    kk: kk_KZ
    kn: kn_IN
    ky: ky_KG
    lo: lo_LA
    lt: lt
    lv: lv_LV
    #me: sr_ME
    me-lat: sr_ME_lat
    me-cyr: sr_ME_cyr
    mk: mk_MK
    ml: ml_IN
    mn: mn_MN
    mr: mr_IN
    ms: ms_MY
    nb: nb_NO
    ne: ne_NP
    nl: nl_NL
    nn: nn_NO
    "no": nb_NO
    oc: oc
    pl: pl
    pt: pt_PT
    ru: ru_RU
    sk: sk_SK
    sl: sl_SI
    so: so_SO
    sq: sq_AL
    sr-cyr: sr_RS_cyr
    sr-lat: sr_RS_lat    
    sv: sv_SE   
    ta: ta_IN
    te: te_IN
    tg: tg_TG
    th: th_TH
    tk: tk
    tr: tr
    tt: tt_RU
    uk: uk_UA
    ur: ur_PK
    uz: uz_UZ
    yi: yi
