#Hunspell dictionaries path
# will look for dictionaries at ~/.local/share/fastspell if empty
dictpath: ""

#This is how hunspell files (.dic and .aff) are named in dictpath
hunspell_codes:
    af: af_ZA
    am: am_ET
    an: an_ES    
    ar: ar
    ast: ast_ES
    awa: awa
    az: az_AZ
    be: be_BY
    bg: bg_BG
    bho: bho
    bn: bn_BD
    bs: bs_BA
    ca: ca_ES
    cs: cs_CZ
    cy: cy_GB
    da: da_DK
    de: de_DE
    en: en_GB
    es: es_ES
    et: et_ET
    fa: fa_IR
    fi: fi_FI
    fo: fo
    fr: fr
    fur: fur
    ga: ga
    gl: gl_ES
    gn: gug
    gu: gu_IN
    hbs_lat: hbs_Lat_HBS
    hbs_cyr: hbs_Cyr_HBS
    he: he_IL
    hi: hi_IN
    hr: hr_HR
    ht: ht_HT
    hu: hu_HU
    id: id_ID
    is: is_IS
    it: it_IT
    iw: he_IL
    kk: kk_KZ
    kn: kn_IN
    ky: ky_KG
    lb: lb_LU
    lo: lo_LA
    lt: lt
    ltg: ltg
    lv: lv_LV
    mag: mag
    mai: mai_IN
    me_lat: sr_ME_lat
    me_cyr: sr_ME_cyr
    mk: mk_MK
    ml: ml_IN
    mn: mn_MN
    mr: mr_IN
    ms: ms_MY
    nb: nb_NO
    ne: ne_NP
    nl: nl_NL
    nn: nn_NO
    "no": nb_NO
    oc: oc
    pap: pap_AW
    pl: pl
    pt: pt_PT
    qu: qu_EC
    ro: ro_RO
    ru: ru_RU
    sc: sc_IT
    sk: sk_SK
    sl: sl_SI
    so: so_SO
    sq: sq_AL
    sr_lat: sr_RS_lat
    sr_cyr: sr_RS_cyr
    sv: sv_SE   
    szl: szl
    ta: ta_IN
    te: te_IN
    tg: tg_TG
    th: th_TH
    ti: ti_ER
    tk: tk
    tl: tl_PH
    tr: tr
    tt: tt_RU
    uk: uk_UA
    ur: ur_PK
    uz: uz_UZ
    vec: vec
    yi: yi
    zsm: ms_MY
