#Target langs (keys) dict for mistakeable languages (values)
similar:
    af: [nl, de]
    am: [ti]
    ast: [es]
    awa: [hi]
    az: [tr]
    be: [ru, uk]    
    bg: [mk, ru]
    bho: [hi]
    bs: [hr, sr_lat, sl] #should add me (not adding because dict is the same as sr)
    ca: [es, oc]
    cs: [sk]
    cy: [ga, en]
    da: [nb, sv]
    es: [gl, ca, ast]
    fa: [ar, az]
    fo: [is, nb, da]
    ga: [cy, en]
    gl: [es, pt]
    gn: [es]
    hbs_lat: [sl]
    hbs_cyr: [ru, mk, bg]
    hi: [mr, ne] #add SD
    hr: [bs, sr_lat, sl] #should add me (not adding because dict is the same as sr)
    ht: [tl]
    id: [ms]
    is: [da, nb, nn, sv]
    iw: [yi]
    kk: [ky, tt, ru]
    ky: [ru, kk, tt, mn]
    lb: [de]
    lv: [lt]
    me_lat: [hr, sl]
    me_cyr: [bg, mk, ru] #
    mk: [bg, sr_cyr, ru]
    mn: [ru, ky, bg]
    mr: [hi]
    ms: [id]
    nb: [da, sv, nn]
    ne: [mr, hi]
    nl: [af]
    nn: [nb, da, sv]
    "no": [da, sv, nn] #same as NB, since dict is the same
    oc: [ca, es]
    #ps: [ar, fa]
    pt: [es, gl]
    ru: [uk, bg]
    sk: [cs, pl]
    sl: [sr_lat, hr, bs]
    so: [en, fi, cy, kn]
    sr_cyr: [mk, bg, ru] #should add me (not adding because dict is the same as sr)
    sr_lat: [bs, hr, sl]
    sv: [da, nb]
    tg: [bg, ru]
    ti: [am]
    tt: [kk, ky, ru] #maybe add BA
    uk: [be, ru, mk, bg]
    ur: [fa, ar]
    uz: [tr]
    yi: [he]
    zsm: [ms, id]
