#Target langs (keys) dict for mistakeable languages (values)
similar:
    ca: [es, ca]
    cs: [sk, cs]    
    da: [da, nb]
    es: [es, gl, ca]
    gl: [es, pt, gl]
    hr: [bs, sr, me, mk, sq, hr]    
    nb: [nn, da, nb]
    nl: [nl, af]
    nn: [nb, da, nn]
    sk: [cs, sk]
